remote_theme: just-the-docs/just-the-docs
title: Laravel Settings
description: A powerful and flexible Laravel package designed to simplify the management of application settings, both at the global and model-specific levels.
